### PR TITLE
Icons added

### PR DESCRIPTION
**Pull request by alchemiker**
Added icons of:

- 112 Suomi
- Anton
- Atom
- Clusterduck
- Flappy Bird (can't believe it doesn't exist already??)
- Git Coach (maybe I should install it myself to learn to not mess up PRs haha)
- Metager (Search)
- Nameless Cat
- Periodic table (combined 2 apps and their respective Pro versions)

Please note: the "Nameless Cat" is bigger than the frame. That's because in the original at Google Play Store it also has its ears clipped a little bit off by the icon borders.

other icons are probably to come in this PR.

### CODE REVIEW

**Comment by Donnnno** [comment]
What's happening with Atom?

image

**Comment by alchemiker** [comment]
I don't know 🤣 

It just looks like that 🤷 idk what the designer thought, I saw it in the request file and thought I had to accept this challenge this time

https://play.google.com/store/apps/details?id=com.subconscious.thrive

grafik

Constructive criticism welcome :D

**Comment by alchemiker** [comment]
@TotallyAvailable sorry I didn't see your comment, I got no notification for it and see it just now! So you ask me to add this three appfilter entries to the already existing apps in the appfilter.xml, right?

**Comment by Donnnno** [comment]
> I don't know 🤣
> 
> It just looks like that 🤷 idk what the designer thought, I saw it in the request file and thought I had to accept this challenge this time
> 
> https://play.google.com/store/apps/details?id=com.subconscious.thrive
> 
> grafik
> 
> Constructive criticism welcome :D

Oh haha uhhhhhh, this is what I made of it: (removed a couple of shapes)
image

**Comment by dgcampbe** [comment]
Omg that icon design. XD

**Comment by alchemiker** [comment]
Thanks @Donnnno !
I'm not sure if it looks better now, but in the end it's your icon pack and I don't use this particular app anyway, meaning I won't have to look at this icon all the time haha

**Comment by Donnnno** [comment]
Idk if it's much better, but at least it's a bit cleaner now 🙃 

Also noticed that you forgot the appfilter, so added it myself :)

**Pull request merged**
