### PR TITLE
Added slither.io icon

### PR DESCRIPTION
**Pull request by andersmmg**

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi! Looks like you've expanded the shape.
image

All icons should have only line elements

**Comment by andersmmg** [comment]
Ah dang it I swear I undid that. I'll have to redo it sometime I guess.

**Comment by wwwwwwari** [comment]
So, I've tried to redraw this icon. It's not going to be exactly the same as what's submitted, but it should still look close enough?
slitherio

**Comment by Donnnno** [comment]
thx @wwwwwwari !

**Pull request closed without merging**
