### PR TITLE
Create BuildReleasePlay.yml

### LINKED ISSUE #2369: Automatic Google Play publishing with a new release
Gonna ask the Delta devs for help with this :)

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
Closes #2369
https://github.com/r0adkll/upload-google-play/tree/master
image

I have implemented the simple method you just need to set the secret in the play release environment 

~at the moment this does not include a changelog~
~for this i need to somehow convert the changelog md to plaintext or have a~ ~second changelog file with almost the same content~

### CODE REVIEW

**Comment by Donnnno** [comment]
Oh damn, this is sick! I will look at setting this up tonight!

**Comment by Donnnno** [comment]
Thank you so much!!! 
I've completed all steps exept for d:
`serviceAccountJsonPlainText`

Where do I have to fill in that?

**Comment by Kaiserdragon2** [comment]
In the settings tab under environments i created one named play release or something similar the should already be a secret prepared

**Comment by Donnnno** [comment]
Ohh so then we're good to go?

**Comment by Kaiserdragon2** [comment]
You need to fill in the secret into the existing variable 
image

**Comment by Donnnno** [comment]
I think I did it?

**Pull request merged**
