### PR TITLE
Automatic Changelog Generation

### LINKED ISSUE #2370: Improve the release script to include changelog in app too.
It would be pretty neat if the release action can add the changelog inside the app too!

https://github.com/Arcticons-Team/Arcticons/blob/main/app/src/main/res/values/changelog.xml

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
Generates Basic changelog  
Fixes #2370
image
Only the marked values are changed
I have implemented a function to do the same for the changelog.md 
image

### CODE REVIEW

**Comment by Donnnno** [comment]
Again, amazing work!

**Comment by Donnnno** [comment]
Interesting, it looks like it doesn't count the new icons when I run the action.
image

**Comment by Kaiserdragon2** [comment]
Weird i have to look at it tomorrow in more detail this should theoretically count all entries in the drawable.xml and the new icons should be in there as well.

**Comment by Donnnno** [comment]
Oh weird, take your time, no rush!

**Comment by Kaiserdragon2** [comment]
Did you run the changelog action standalone or did you run the prepare release action

**Pull request merged**
