### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by dumdus**
Icon is called howwefeel.svg and it I'd for the how we feel app. :)

### CODE REVIEW

**Comment by Donnnno** [comment]
Congrats on your first icon! 

Just need some more info to make it actually work.

Please check out step four from the contribution guide :) 
https://github.com/Arcticons-Team/Arcticons/blob/main/CONTRIBUTING.md#quick-guide

**Comment by dumdus** [comment]
@Donnnno don’t know what to do there, can you help me? And I’m on mobile

**Comment by Donnnno** [comment]
@dumdus please download icon request here: https://play.google.com/store/apps/details?id=de.kaiserdragon.iconrequest

and click update existing, then select your app and paste the code here :)

**Comment by Donnnno** [comment]
nevermind, found it :)

**Pull request merged**
