### PR TITLE
Fix combining the appfilterfiles & allow action only run 1 at the time

### PR DESCRIPTION
**Pull request by Kaiserdragon2**

### CODE REVIEW

**Comment by Donnnno** [comment]
This thing just won't get fixed that easily, huh?

**Comment by Kaiserdragon2** [comment]
It's hard to test if you need to interact with pull requests and the repo itself

**Comment by Donnnno** [comment]
I can imagine, I've given you write access so that you don't have to wait for me every single time :)

**Comment by Kaiserdragon2** [comment]
Now it works

**Pull request merged**
