### PR TITLE
New 36 icons

### PR DESCRIPTION
**Pull request by gewaleelek**
Please let me know if there's any problem with my files. 🙂

-----

Add new icons:

* Coffee2U
* iQIYI
* Supersports
* Truevisions
* TTP Cargo

Add icons by updating appfilter.xml only:

* ENNXO
* Activity Launcher fork

Update contributors.xml per the contribution guide.

### CODE REVIEW

**Comment by gewaleelek** [comment]
New icons:

* Gorebox

* Solo Leveling Arise (I have no ability to draw the ever handsome Sung Jin Woo in a 48 by 48 pixel area so I take liberties with the "S" from the anime logo; please feel free to suggest better ideas)

* OpenTune for #2259

* Instagram Lite for #2252 (not sure if that is going to solve the user's issue)

Any ?'s please let me know.

**Comment by gewaleelek** [comment]
I just added 5 new icons for 3 Pokemon games in a953904.

**Comment by gewaleelek** [comment]
I just added 3 new icons for Original Sound, Royal Match and Mountain Bike Xtreme in 9860e4b.

**Comment by sbstratos79** [comment]
Hi. I tried creating a more accurate Solo Leveling Arise logo. Let me know if you like this one better. I will create a pull request in that case.
[Solo Leveling Arise](https://github.com/user-attachments/assets/bccbf052-06c1-46b0-b62a-62c33cb88b24)

**Comment by Donnnno** [comment]
Fantastic work!!!

**Pull request merged**
