### PR TITLE
Emailparser with downloader script

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
This adds a download function that downloads every Unread email in the Inbox after that i set it to read.
I have added a powershell script to set the variables for the login into the email server.
this needs to be run in the same terminal as the python script.
It needs to be edited with the proper credentials. (Please save it somewhere safe. Don't accidentally push it to GitHub.)

The script is written in a way to be easily integrated in a workflow that could run on a schedule to update the request page.

### CODE REVIEW

**Comment by Donnnno** [comment]
Interesting! 
How I do it now is by downloading all mails containing "Arcticons .... Icon request" to a folder with Thunderbird, and running the script.

**Comment by Kaiserdragon2** [comment]
Good to know i will implement a function that filters the subject.
Also the email parser needs to be updated that no emails are printed to the log.

**Comment by Donnnno** [comment]
Oh wow, that's just amazing!! 
Is it also possible to delete the mails instead of it getting read? 
Also gotta check out on how to configure this with Proton Mail.

**Comment by Donnnno** [comment]
Oh:
image

🙃

**Comment by Donnnno** [comment]
I'm planning on moving the Arcticons domain to Cloudflare in the future, I think they provide free mail adress features, so that might be worth checking out then.

**Comment by Donnnno** [comment]
Oh, why did you close this one? 👀

**Comment by Kaiserdragon2** [comment]
Wasn't going was accidentally will reopen

**Comment by Donnnno** [comment]
Ah okey!
It's still planned, but I'm waiting a bit longer to switch hosting providers because I paid for a full year (it ends next month).

**Pull request merged**
