### PR TITLE
Added Icon for Amazon Luna

### PR DESCRIPTION
**Pull request by Cod3rQwerty**

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, please follow our contribution guide carefully!
We need a line for the appfilter, and rename the icon to amazon_luna

**Comment by gewaleelek** [comment]
From the request dashboard, the appfilter line is probably
```
<!-- Amazon Luna -->
<item component="ComponentInfo{com.amazon.spiderpork/com.amazon.spiderpork.activities.MainActivity}" drawable="amazon_luna"/>
```

**Comment by Cod3rQwerty** [comment]
> Hi, please follow our contribution guide carefully! We need a line for the appfilter, and rename the icon to amazon_luna

I've done all the above,  using @gewaleelek 's appfilter line. Are there any problems still? Sorry for the late response 😅

**Comment by gewaleelek** [comment]
I've already included the icon in #2372 earlier today (see ed0173a) though I'm ok with either being merged.

**Pull request closed without merging**
