### PR TITLE
Added Run config for new release

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
image

### CODE REVIEW

**Comment by Donnnno** [comment]
Nicee

**Comment by Donnnno** [comment]
Uh oh, I'm getting this error, I searched for solutions and tried some things, but it doesn't go away :s 

image

**Comment by Kaiserdragon2** [comment]
https://github.com/Arcticons-Team/Arcticons/blob/main/preparehelper%2Fsrc%2Fmain%2Fjava%2Fcom%2Fdonnnno%2Farcticons%2Fhelper%2FPrepareRelease.java

In line 62 change python3 to python that should work

It seems on your system there is some alias set for python3 that doesn't lead anywhere

**Comment by Donnnno** [comment]
Thanks!

Windows....
806a6389-656c-460f-be88-d3a31b4e5036-500728159

**Pull request merged**
