### PR TITLE
Email Parser Improvements 

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
~At the moment it is possible that the naming of a drawable changes when the a new entry with the same name appears.
it could be renamed from `icon` to `icon_1` this would lead to switched icons.~ <- Need to check my code properly before assuming things.
Also the the updateble file isn't parsed at the monet and get only overwritten if not all possible update are processed before a run of the script the are lost.

These changes should fix these issues!
Draft until properly tested!!!

### CODE REVIEW

**Comment by Donnnno** [comment]
Not really related, but I noticed that the prepare release script doesn't clear the previous new icons anymore :s 

image
image
image

**Comment by Donnnno** [comment]
Got an error!

```
Traceback (most recent call last):
  File "C:\Users\o-nn-\Documents\GitHub\Arcticons\scripts\email_parser.py", line 321, in <module>
    parser.main()
  File "C:\Users\o-nn-\Documents\GitHub\Arcticons\scripts\email_parser.py", line 300, in main
    self.parse_existing(self.update_block_query,self.updatable_path)
  File "C:\Users\o-nn-\Documents\GitHub\Arcticons\scripts\email_parser.py", line 64, in parse_existing
    self.apps[element_info['ComponentInfo']]['requestDate'] = float(element_info['requestDate']) if element_info['requestDate'] is not None else mktime(date.today().timetuple())
                                                                                                    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'requestDate'
```

Let me know if you need some mails to test it with

**Comment by Kaiserdragon2** [comment]
> Not really related, but I noticed that the prepare release script doesn't clear the previous new icons anymore :s
> 
> image image image

i think the issue is the missing --new in your command 
usage: preparerelease.py [-h] [--checkonly] [--new] ARCTICONS_DIR

positional arguments:
  ARCTICONS_DIR  Path to the Arcticons directory

options:
  -h, --help     show this help message and exit
  --checkonly    Run checks only
  --new          Run a new Release

**Comment by Kaiserdragon2** [comment]
> Got an error!
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\o-nn-\Documents\GitHub\Arcticons\scripts\email_parser.py", line 321, in <module>
>     parser.main()
>   File "C:\Users\o-nn-\Documents\GitHub\Arcticons\scripts\email_parser.py", line 300, in main
>     self.parse_existing(self.update_block_query,self.updatable_path)
>   File "C:\Users\o-nn-\Documents\GitHub\Arcticons\scripts\email_parser.py", line 64, in parse_existing
>     self.apps[element_info['ComponentInfo']]['requestDate'] = float(element_info['requestDate']) if element_info['requestDate'] is not None else mktime(date.today().timetuple())
>                                                                                                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^
> KeyError: 'requestDate'
> ```
> 
> Let me know if you need some mails to test it with

this was somehow expected because the updatable doesn't have a request date in it

**Comment by Donnnno** [comment]
> > Not really related, but I noticed that the prepare release script doesn't clear the previous new icons anymore :s
> > image image image
> 
> i think the issue is the missing --new in your command i added it so it is possible to run the script then again add icons and the previous ones are still in new usage: preparerelease.py [-h] [--checkonly] [--new] ARCTICONS_DIR
> 
> positional arguments: ARCTICONS_DIR Path to the Arcticons directory
> 
> options: -h, --help show this help message and exit --checkonly Run checks only --new Run a new Release

oOps my bad 🙃!

**Comment by Donnnno** [comment]
tested it, works great! Awesome job again!

**Pull request merged**
