### PR TITLE
Add 6 icons

### PR DESCRIPTION
**Pull request by Th3Third3ye**

### CODE REVIEW

**Comment by Donnnno** [comment]
Fantastic work on the icons! 
One small thing, you should update your template files, the square icons are a bit rounder now ;)

**Comment by Donnnno** [comment]
Also, looks like you've deleted the appfilter list completely, please only add your entries next time!
Will add your PR into a fresh commit

**Comment by Donnnno** [comment]
Oh, and while I'm at it, please keep your icon names the same as the drawable ones :)

**Comment by Th3Third3ye** [comment]
About the names I got confused even though I knew that, sorry, I will correct everything and check the new templates!!

**Comment by Donnnno** [comment]
No worries! Thanks for your work!

**Pull request closed without merging**
