### PR TITLE
Add 'Dropsync'

### PR DESCRIPTION
**Pull request by frank-murphy**
Let me know if there's anything I need to change.

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, nice work. 
You'll need to provide some lines of code to the appfilter.xml file in order for it to work. You can gather it with icon request -> https://github.com/Kaiserdragon2/IconRequest/

**Comment by frank-murphy** [comment]
Updated appfilter.xml as asked.

**Comment by Donnnno** [comment]
thank you :)

**Comment by Donnnno** [comment]
just fixed the line-width and made it white. (some things to keep in mind for the future )

**Pull request merged**
