### PR TITLE
new icon for Guardian tales

### PR DESCRIPTION
**Pull request by Sande-Santhosh**

### CODE REVIEW

**Comment by Donnnno** [comment]
Simplified the icons a bit more :)
image

**Comment by Sande-Santhosh** [comment]
> Simplified the icons a bit more :) image

Looks good

**Comment by Donnnno** [comment]
Also make sure that the icon name corresponds to the one in the appfilter next time ! :)

**Comment by Sande-Santhosh** [comment]
> Also make sure that the icon name corresponds to the one in the appfilter next time ! :)

Sure

**Pull request merged**
