### PR TITLE
WepP Icons

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
#2227

### CODE REVIEW

**Comment by Kaiserdragon2** [comment]
i converted the existing icons with android studio and changed the script to create webp icons instead of png

**Comment by Donnnno** [comment]
fantastic, I'm just prepping a new release.
You haven't converted the new ones yet, right?

**Comment by Kaiserdragon2** [comment]
The new ones i haven't converted

**Comment by Donnnno** [comment]
Thank you so much for converting this, really curious to see how this turns out with the next release!

**Pull request merged**
