### PR TITLE
Initial attempt to add breezy weather support to the main app.

### PR DESCRIPTION
**Pull request by dgcampbe**
There are probably some issues. Feel free to help verify that I did this right. :stuck_out_tongue:

### CODE REVIEW

**Comment by Donnnno** [comment]
I tested it, but it didn't seem to work yet.
It probably needs to be put into all the right folders first?

**Comment by Kaiserdragon2** [comment]
I have done some tests and it stops working as soon as the is a suffix like .debug or .light at the end of the app

**Comment by Kaiserdragon2** [comment]
Did you run the preparerelease.py? Only normal normal had worked and i had
modified the app before and removed all sorts of stuff to test what impacts
the implementation (ui and candybar) where non existent. While implementing
it in the Icon Request app to test if it works was as easy as adding these
lines of code to the manifest file. I will try to test a bit more why it
does not work with the added suffix or if there is something else that
affects this

**Comment by Donnnno** [comment]
I .... I did not run the script -,-

**Comment by Donnnno** [comment]
It works on the emulator!

(We might need to think dynamic day and night sceming for the widgets and in the app) 


image
image

**Comment by Donnnno** [comment]
How's this? 
image

**Comment by dgcampbe** [comment]
Those icons look great! Thanks @Kaiserdragon2 for fixing the position of the metadata tags.

**Comment by dgcampbe** [comment]
Feel free to merge when ready. :smile:

**Comment by Donnnno** [comment]
Want to test if it works dark& night modus, gonna do it tomorrow :)

**Comment by Donnnno** [comment]
It respects the user preferences now!
image
image

**Comment by min7-i** [comment]
I saw your issue in the Breezy Weather repo. 

Just a small hint: If I remember correctly, as long as you only provide weather icons, you don't need to create the xml files for other resources like animated icons, sun & moon, etc.:
- app/src/main/res/xml/breezy_icon_provider_animator_filter.xml
- app/src/main/res/xml/breezy_icon_provider_shortcut_filter.xml
- app/src/main/res/xml/breezy_icon_provider_sun_moon_filter.xml

Then you can also leave that out in the manifest:
```
        <meta-data
            android:name="org.breezyweather.ANIMATOR_FILTER"
            android:resource="@xml/breezy_icon_provider_animator_filter" />
        <meta-data
            android:name="org.breezyweather.SHORTCUT_FILTER"
            android:resource="@xml/breezy_icon_provider_shortcut_filter" />
        <meta-data
            android:name="org.breezyweather.SUN_MOON_FILTER"
            android:resource="@xml/breezy_icon_provider_sun_moon_filter" />
```

Breezy Weather will automatically fall back to the defaults if those resources are not provided.

**Comment by Donnnno** [comment]
Thanks for the suggestions @min7-i ! 
I'm working on shortcuts, and a sun & moon icon now. But I don't think we'll need the animator (it would look weird with transparent icons, I guess)

**Comment by Donnnno** [comment]
For some reason, the material you version doesn't show the icons: 

image

Shortcuts should work tho
image

**Pull request merged**
