### PR TITLE
Adding 19 new icons.

### PR DESCRIPTION
**Pull request by duese**

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, looks like you removed the entire appfilter! You must only add yours to the top, bottom, basically anywhere, but don't override the other lines 🙃

**Comment by Donnnno** [comment]
can you rebase with the main branch here and add your icons again? I can't check it out due to the many changes

**Comment by Donnnno** [comment]
Hi, thanks!
I've taken a look at your icons, great work! 
I'm adding them in a fresh pr (for some reason I can't open this one with GitHub desktop)

Here are some things I noticed:

- make sure to use the updated basic square icon, it has slightly rounder corners, also the text was really weird here:
image

**Comment by duese** [comment]
Thanks for the hint. Had to run the SVGs through several tools to get the discouraged SVG elements removed as stated in the docs. Maybe they got crumbled in the process of doing so.

**Comment by Donnnno** [comment]
Oh don't worry about the transform elements, I'll take care of that stuff, when you upload them :-)

**Comment by duese** [comment]
Okay, good to hear. 😃 But maybe your workload could be reduced if there's a section in the documentation explaining how to get rid of the transform elements in the first place.

**Comment by Donnnno** [comment]
I think it can be removed from the contribution guide altogether, we used an old export method that didn't support it, but the newer one should have the functionality.

**Pull request closed without merging**
