### PR TITLE
Add 160+ icons

### PR DESCRIPTION
**Pull request by wwwwwwari**
This PR includes

* 60 new icons
* 2 new apps using existing icons (USPS Mobile and Xbox)
* An icon update for Symphony

-----

**Edit (Jul 29)**
* Some icons are added; see the details below

### CODE REVIEW

**Comment by Kaiserdragon2** [comment]
Thats almost enough for a new release.

**Comment by Donnnno** [comment]
Wari, where did you find the time to do all of this? 😵‍💫

**Comment by wwwwwwari** [comment]
> Wari, where did you find the time to do all of this? 😵‍💫

I used the strategy called unemployment, 3-month semester break (ending soon) and cherry-picking easy icons only. 😉

**Comment by Donnnno** [comment]
Am going through all icons from the bottom to the top (idk why).

Some oddities I already found, basically all of them are stretched letters. I'm not a fan of those, it makes me think of the brat album cover.

Still have to check the other half, but doing that tomorrow probably! 

Amazing work <3 ! 

image

image

image



Charli-XCX-Brat-2200352136

**Comment by wwwwwwari** [comment]
No-font-stretch noted. Thank you for going though them!

**Comment by wwwwwwari** [comment]
I just add a few more icons! The compound paths should not be there anymore, I think?

(My semester starts tomorrow so I can't really procrastinate studying to make more icons anymore 🤣 Do tell me if there's anything I need to fix though!)

**Comment by Donnnno** [comment]
😵‍💫😵‍💫😵‍💫😵‍💫😵‍💫

**Comment by Donnnno** [comment]
❤️

**Pull request merged**
