### PR TITLE
Five new icons

### PR DESCRIPTION
**Pull request by savetier**
- JÖ Austria
- Spar
- Polish-English Dictionary
- Soloviy
- Dust Messenger

Added some lines in appfiler.xml for Unicredit, Ukrainian-English Dictionary, ProtonVPN

### CODE REVIEW

**Comment by Donnnno** [comment]
Nice work! 
I had to change some things tho:

image

Some icons did have clipping masks, or sloppy lines. The sizing wrong too (please check the contribution guide!)

**Comment by savetier** [comment]
Hi Donnnno, thanks for the changes! Do you know any guide (e.g. on yt) where I could learn, how to make nice round lines? Thx!

**Comment by Donnnno** [comment]
The Bézier Game gives a pretty good idea how the curves work: https://bezier.method.ac/

**Comment by savetier** [comment]
Wow, this is awesome! Thanks so much :)

**Pull request merged**
