### PR TITLE
added 16 new icons

### PR DESCRIPTION
**Pull request by JapanYoshi**
This pull requests adds SVG icons to the following 6 apps:

* Doodle Jump
* JD.com (may have been requested under the native Chinese name, 京东)
* My Boy!
* Smule Sing
* Tim Hortons
* UNIQLO

### CODE REVIEW

**Comment by JapanYoshi** [comment]
```
<!-- Doodle Jump -->
<item component="ComponentInfo{com.lima.doodlejump/com.limasky.doodlejumpandroid.MainActivity}" drawable="doodle_jump"/>

<!-- JD.com / 京东 -->
<item component="ComponentInfo{com.jingdong.app.mall/com.jingdong.app.mall.main.MainActivity}" drawable="jd_com"/>

<!-- My Boy! Free -->
<item component="ComponentInfo{com.fastemulator.gbafree/com.fastemulator.gba.MainActivity}" drawable="my_boy"/>

<!-- Smule -->
<item component="ComponentInfo{com.smule.singandroid/com.smule.singandroid.StartupActivity}" drawable="smule"/>

<!-- Tim Hortons -->
<item component="ComponentInfo{digital.rbi.timhortons/digital.rbi.timhortons.MainActivity}" drawable="tim_hortons"/>

<!-- UNIQLO -->
<item component="ComponentInfo{com.uniqlo.in.catalogue/com.uniqlo.ja.catalogue.view.mobile.startup.StartupActivity}" drawable="uniqlo"/>
```

**Comment by JapanYoshi** [comment]
Noticed that the non-free version of My Boy! has an icon already, do you think my new one is better?

my_boy_comparison

**Comment by Donnnno** [comment]
Fantastic work! I removed myboy free and uber russia in favor of my_boy & uber.

**Comment by Donnnno** [comment]
> Noticed that the non-free version of My Boy! has an icon already, do you think my new one is better?
> 
> my_boy_comparison

Yours is better indeed!

**Pull request merged**
