### PR TITLE
Lets go Faster (Improve Preparerelease script)

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
Use Cairosvg instead of inkscape to create png
improve runtime for current build from 390s to 12s on my machine

### CODE REVIEW

**Comment by Donnnno** [comment]
Wow, this is absolutely amazing! This is gonna save so much time!!!

**Comment by Donnnno** [comment]
might wanna check this tho:

image

idk what I have to fix now 😅

**Comment by Donnnno** [comment]
Just tested it, something's happening here probably:

image

**Comment by Donnnno** [comment]
Also the iconpack.xml files are unnecessary, so we probably want to remove those as well :)

**Comment by Kaiserdragon2** [comment]
> Also the iconpack.xml files are unnecessary, so we probably want to remove those as well :) 

Will look into some optimisation of the script

**Pull request merged**
