### PR TITLE
Small icon and appfilter changes

### PR DESCRIPTION
**Pull request by wwwwwwari**
This PR includes mostly minor changes

1. Add several variants of Thai TV apps to use 'thai_tv.svg' icon    
2. Adjust Comdirect PhotoTAN's icon to use outline instead of the default font - #2117
3. Add missing entries for Claro Flex and Sound Meter in the appfilter.xml (icons already exist) - #2136

### CODE REVIEW

**Comment by Donnnno** [comment]
image
 
More minimalism™️!

**Comment by wwwwwwari** [comment]
> image
> 
> More minimalism™️!

Since the OP of the linked issue wanted them to look alike, should we also update [comdirect.svg](https://github.com/Arcticons-Team/Arcticons/blob/main/icons%2Fblack%2Fcomdirect.svg) to match?

**Comment by Donnnno** [comment]
Hmm that C is pretty big, so that would feel maybe too empty then?

**Comment by wwwwwwari** [comment]
It'll be kind of empty, yes, but I kind of agree with the OP of that issue that the 2 icons should look the same since it's the same company's apps. I'm thinking we could do one of these:

1. Copy the C of comdirect_phototan.svg to comdirect.svg - the comdirect icon will become kind of empty as you said
2. Copy the C of comdirect.svg to comdirect_phototan.svg - the phototan icon will look not minimal enough (which is what you just fixed)
3. Do 1 or 2 and add the other design as alt icons?

I'm leaning to just go with the outlines for both of them and add the thin line designs as alts - thoughts? 🤔

**Pull request merged**
