### PR TITLE
some new icons

### PR DESCRIPTION
**Pull request by npnpatidar**
banque_pop,
crex,
octopus,
pathbuilder2e,
heat_it,
voter_helpline,
article_reader,
bharatpe,
blocksite,
boat_crest,
bukalapak,
campuscare,
clozemaster,
cmf_watch,
cmrl,
comic_geeks,
cross_dj,
deku_sms,
destiny,
ds_get,
edifier_connect,
enki,
gaana,
giphy,
gopay,
greentuber,
gumtree,
happn,
headway,
hipaint,
idgovpt,
imagesearchman,
instaddr,
intel_unison,
j_and_t express,
jenius,
kids_space,
letsview,
light_novel_library,
linksys,
load_shedding_notifier,
lwp_,
mi_entel_peru,
mi_wi_fi,
mon_compte,
multiple_accounts,
mytim,
neon,
notein,
nova,
ola_electric,
parkmobile,
pc_remote,
pillars,
plurall,
rocket_money,
safepal,
skit,
skullcandy,
smart_hq,
square,
starmaker,
swap_no_root,
tata_cliq,
to_do_list,
tracker_network,
trading_212,
transmission_btc,
tripview,
unicredit,
vancity,
vaulty,
wifi_password,
wink,
zelle,
zorin_connect,
icemobile_lenta,

### CODE REVIEW

**Comment by npnpatidar** [comment]
some edits may be required

**Comment by Donnnno** [comment]
Wow! That's a lot of icons

**Comment by Donnnno** [comment]
Gonna check and make some edits in batches :) 
started with a-c:
image

**Comment by Donnnno** [comment]
Great work!
I've changed sizing things, mostly, found many circles that weren't fully round and lines that weren't straight.

**Comment by npnpatidar** [comment]
Thanks for patience.  I create icons in vector asset creator and it does not allow to import svg files for templates  and has many other  limitations,  that's why that kind of perfection is not found.  Although I do use grid and snapping but to no avail.

**Pull request merged**
