### PR TITLE
HROne Inbox 2.0

### PR DESCRIPTION
**Pull request by aryanjha256**
com.hrone.android

### CODE REVIEW

**Comment by Donnnno** [comment]
Please add the appfilter entry for your app to the appfilter:
https://docs.arcticons.com/contribute/github-guide#adding-your-icons

**Comment by Npepperlinux** [comment]
```xml
<appfilter>

	<!-- HROne Inbox V2 -->
	<item component="ComponentInfo{com.hrone.android/com.hrone.android.app.LoginActivity}" drawable="hrone_inbox_v2"/>

</appfilter>
```

**Comment by Donnnno** [comment]
Thanks @Npepperlinux !

**Comment by Donnnno** [comment]
Nice work on the icon, but be sure to follow the contributing guide carefully next time!

**Comment by aryanjha256** [comment]
Sure, @Donnnno .
thanks for merging the pr.

**Pull request merged**
