### PR TITLE
Six new icons for some apps

### PR DESCRIPTION
**Pull request by GitEnte**
Apps that have new icons are:
WDR aktuell, 360° online, Andor, Mutti-App, TK Husteblume

This is my first time making and adding icons btw, so it should defenitily be checked before merging :).

### CODE REVIEW

**Comment by Donnnno** [comment]
Hi, congrats on your first contribution!
We need to change some things, as in its current stage I can't merge them!

- we only use lines, looks like you used lines and rectangular shapes. Also the line-width is inconsistent here
image

That applies here as well
image

Also, please use the SVG font from the template folder, instead of the otf typeface

image



Please check our contribution guide carefully: https://docs.arcticons.com/contribute/creating-icons

**Comment by GitEnte** [comment]
Screenshot 2024-08-03 225247
Screenshot 2024-08-01 205026
I also noticed that in the arcticons_font.svg file the lines on some letters, only noticed the 0 and R, stand out of the letter in a way that seems weird to me.

**Comment by GitEnte** [comment]
Screenshot 2024-08-05 133302
Screenshot 2024-08-05 133845
I noticed that some of the lines in the letters 0 and R stand out in weird and out of place ways. Is this intentional?

**Comment by Donnnno** [comment]
Oh that's a bug, I'll take a look at it!

**Comment by GitEnte** [comment]
Does anything need further changing?

**Comment by Donnnno** [comment]
Great work!

**Pull request merged**
