### PR TITLE
Add 4 icons

### PR DESCRIPTION
**Pull request by DeltriDev**
Twin edge, [eortologio](https://play.google.com/store/apps/details?id=com.eortes2&hl=en_US), [tinyview](https://play.google.com/store/apps/details?id=com.newput.tinyview&pcampaignid=web_share) and [battery widget](https://play.google.com/store/apps/details?id=com.lstapps.batterywidget&hl=en_US)
I also added the stuff it needs in appfilter.xml and added my name on contributors.xml.

### CODE REVIEW

**Comment by Kaiserdragon2** [comment]
you seem to have accidentally uploaded the battery widget as an png instead of an svg

**Comment by DeltriDev** [comment]
> you seem to have accidentally uploaded the battery widget as an png instead of an svg

woops! thanks, lemme fix it

**Comment by DeltriDev** [comment]
and ok, i think it's fixed now

**Comment by Donnnno** [comment]
Thanks for the icons, I've made some tiny adjustments to them.

Also noticed that the walrus shape wasn't made out of one line, fixed that now. But try to make shapes out of one line, it will look a lot cleaner in the end.

Scherm­afbeelding 2024-01-07 om 14 04 39

Keep up the good work!

**Comment by DeltriDev** [comment]
Thanks! yeah, i'm still learning the stuff lol didn't know i can connect them

**Pull request merged**
