### PR TITLE
Add icons

### PR DESCRIPTION
**Pull request by aaofyi**
Icons:
---
Google Voice (added icon + appfilter)
com.google.android.apps.googlevoice/com.google.android.apps.googlevoice.SplashActivity
https://play.google.com/store/apps/details?id=com.google.android.apps.googlevoice
googlevoice

Kickstarter (added icon + appfilter) #536 
com.kickstarter.kickstarter/com.kickstarter.ui.activities.DiscoveryActivity
https://play.google.com/store/apps/details?id=com.kickstarter.kickstarter
kickstarter

Geizhals (added icon + appfilter) #535 
at.geizhals.pv/at.geizhals.pv.GeizhalsSplashScreen
https://play.google.com/store/apps/details?id=at.geizhals.pv
< This one might be better as "letterg" but I figure I'd let maintainers decide on it. >
geizhals

aCalendar (added icon + appfilter) #436 
org.withouthat.acalendar/org.withouthat.acalendar.ACalendar
https://play.google.com/store/apps/details?id=org.withouthat.acalendar
calendara

Trust Wallet (added icon + appfilter) #469 
Trust Wallet
com.wallet.crypto.trustapp/com.wallet.crypto.trustapp.ui.start.activity.StartActivity
https://play.google.com/store/apps/details?id=com.wallet.crypto.trustapp
shieldt

Appfilter:
---
Xbox Game Pass (added appfilter) [xbox] #536 
com.gamepass.beta/com.gamepass.MainActivity
https://play.google.com/store/apps/details?id=com.gamepass.beta

Emerald Dialer (added appfilter) [phone] #508 
ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity
https://f-droid.org/en/packages/ru.henridellal.dialer/

Nextcloud Services (added appfilter) [nextcloud] #508 
com.polar.nextcloudservices/com.polar.nextcloudservices.SettingsActivity
https://f-droid.org/en/packages/com.polar.nextcloudservices/

Webank (added appfilter) [letterw] #506 
com.opentecheng.android.webank/com.bancobpm.views.splash.SplashActivity
https://f-droid.org/en/packages/com.opentecheng.android.webank/

Sony Calculator (added appfilter) [calculator] #436 
com.sonymobile.exactcalculator/com.sonymobile.exactcalculator.Calculator
https://f-droid.org/en/packages/com.sonymobile.exactcalculator/

Sony Phone (added appfilter) [phone] #436 
com.sonymobile.android.dialer/com.android.dialer.app.DialtactsActivity
https://f-droid.org/en/packages/com.sonymobile.android.dialer/

Music Folder Player Full (added appfilter) [foldermusic] #436 
de.zorillasoft.musicfolderplayer.donate/de.zorillasoft.musicfolderplayer.donate.FolderBrowser
https://play.google.com/store/apps/details?id=de.zorillasoft.musicfolderplayer.donate

SIM Toolkit (added appfilter) [sim] #436 
com.android.stk/com.android.stk.StkMainLauncher
https://f-droid.org/en/packages/com.android.stk/

Google Pinyin Input (added appfilter) [keyboard] #486 
com.google.android.inputmethod.pinyin/com.google.android.apps.inputmethod.libs.framework.core.LauncherActivity
https://play.google.com/store/apps/details?id=com.google.android.inputmethod.pinyin

### CODE REVIEW

**Comment by Thewisem** [comment]
Doesn't that look like whatsapp?

**Comment by aa0-fyi** [comment]
> Doesn't that look like whatsapp?

https://en.m.wikipedia.org/wiki/WhatsApp#/media/File%3AWhatsApp.svg

https://commons.m.wikimedia.org/wiki/File:Google_Voice_icon_(2018-2020).svg

https://commons.m.wikimedia.org/wiki/File:Hangouts_icon.svg

Yes they share many similarities, the primary difference being the location of the bubble on the official icons. This bubble was pulled from this icon packs Google hangouts logo, which I think is also right in having its own icon.

There are many other very similar icons in the icon pack for service-specific logos. if we want to use a general icon for both instead, I don't think the icon should be the Whatsapp logo.

**Comment by aa0-fyi** [comment]
I can't change googles logo choice, take it up with them. You are welcome to do it yourself.

**Comment by Donnnno** [comment]
Hahahaha, great work!!!

**Pull request merged**
